### ISSUE TITLE
Link to Example Demo is broken

### ISSUE THREAD

**Issue by bobmonsour** [11ty/eleventy-upgrade-help#4]
At the end of the Readme, there's a link to an Example Demo that goes to a 404.

**Comment by zachleat** [comment]
This one? https://github.com/11ty/demo-eleventy-upgrade-help

**Comment by bobmonsour** [comment]
Yes

**Comment by zachleat** [comment]
oh, it’s private 😅

**Comment by zachleat** [comment]
back in action, sorry about that!
